### ISSUE TITLE
Implement formatting for output as it is in the spec

### ISSUE THREAD

**Issue by thejhh** [sendanor/ib#1]
Currently only some of the spec is implemented.

For example, the data is printed as JSON by default, instead of record list format.

 * [x]  #6 Record type
 * [x]  #10 Get property of object
 * [ ]  #5 @ as a pointer to the object itself
 * [ ]  #4 Select output type for lists

**Comment by thejhh** [comment]
The record list format has been implemented #6

**Comment by thejhh** [comment]
Added #10 for another specific issue
